name: Update Preview DB

on:
  push:
    branches:
      - main

jobs:
  update-preview-db:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v3

      # 2️⃣ Installer Supabase CLI
      - name: Install Supabase CLI
        run: |
          curl -fsSL https://cdn.jsdelivr.net/npm/supabase-cli@1.84.0/install.sh | bash
          echo "$HOME/.supabase/bin" >> $GITHUB_PATH

      # 3️⃣ Vérifier si migrations/seeds ont changé
      - name: Check if migrations or seeds changed
        id: changes
        run: |
          git fetch origin main
          CHANGED=$(git diff --name-only origin/main HEAD | grep -E '^(migrations/|seeds/)' || true)
          echo "changed_files=$CHANGED" >> $GITHUB_OUTPUT
          if [ -z "$CHANGED" ]; then
            echo "No migrations or seeds changed. Skipping DB update."
          else
            echo "Detected changes in migrations/seeds:"
            echo "$CHANGED"
          fi

      # 4️⃣ Reset, push et seed DB en un seul step si changements
      - name: Reset, Push and Seed Preview DB
        if: steps.changes.outputs.changed_files != ''
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN_PREVIEW }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF_PREVIEW }}
        run: |
          echo "🔄 Resetting preview DB..."
          supabase db reset --project-ref $SUPABASE_PROJECT_REF --force

          echo "⬆️ Pushing migrations..."
          supabase db push --project-ref $SUPABASE_PROJECT_REF

          echo "🌱 Seeding preview DB..."
          # Si tu as plusieurs fichiers seeds, tu peux faire une boucle
          for seed_file in seeds/*.sql; do
            echo "Seeding $seed_file..."
            supabase db query --file $seed_file --project-ref $SUPABASE_PROJECT_REF
          done

          echo "✅ Preview DB updated successfully!"
