name: Update Prod DB

on:
  workflow_dispatch:

jobs:
  push-db-prod:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v3

      # 2️⃣ Installer Supabase CLI
      - name: Install Supabase CLI
        run: |
          curl -fsSL https://cdn.jsdelivr.net/npm/supabase-cli@1.84.0/install.sh | bash
          echo "$HOME/.supabase/bin" >> $GITHUB_PATH

      # 3️⃣ Reset, push et seed DB en un seul step
      - name: Reset, Push and Seed Preview DB
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF_PROD }}
        run: |
          echo "🔗 Linking prod DB"
          npx supabase link --project-ref $SUPABASE_PROJECT_REF
          echo "✅ Pushing DB"
          npx supabase db push
          echo "✅ Prod DB updated successfully!"
