name: Submit App

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to submit'
        required: true
        default: 'ios'

jobs:
  build-and-submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Step Supabase CLI
      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Apply Supabase migrations if changed
        run: |
          echo "🔄 Pushing migrations..."
          supabase db push --project-ref ${{ secrets.SUPABASE_PROJECT_REF_PROD }} --token ${{ secrets.SUPABASE_ACCESS_TOKEN_PROD }} --yes
          echo "✅ Migrations applied to production."
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN_PROD }}

      - uses: expo/expo-github-action@v7
        with:
          expo-version: latest

      - name: Install dependencies
        run: npm install

      - name: Build & Submit
        run: |
          if [ "${{ github.event.inputs.platform }}" = "ios" ]; then
            echo "🔄 Building iOS app..."
            eas build --platform ios --profile production
            echo "🔄 Submitting iOS app..."
            eas submit --platform ios
            echo "✅ iOS app submitted."
          else
            echo "🔄 Building Android app..."
            eas build --platform android --profile production
            echo "🔄 Submitting Android app..."
            eas submit --platform android
            echo "✅ Android app submitted."
          fi
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
          GOOGLE_PLAY_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_PLAY_JSON }}
